const $=q=>document.querySelector(q),ls=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},sv=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let seed=11;const R=()=>(seed=seed*16807%2147483647)/2147483647,ri=(a,b)=>a+Math.floor(R()*(b-a+1));
const ST={"Bihar":["Patna","Gaya","Muzaffarpur","Purnia","Bhagalpur"],"Uttar Pradesh":["Varanasi","Kanpur","Lucknow","Gorakhpur"],"Madhya Pradesh":["Bhopal","Indore","Jabalpur"],"Rajasthan":["Jaipur","Jodhpur","Udaipur"],"Maharashtra":["Pune","Nagpur","Nashik"],"Karnataka":["Mysuru","Belagavi"],"Tamil Nadu":["Chennai","Madurai"],"Gujarat":["Surat","Rajkot"]},SN=Object.keys(ST);
const CATS=["Roads","Bridges","Education","Healthcare","Water Supply","Sanitation","Community Centres","Electricity","Irrigation","Sports"],VEN=["Apex Infra","Bharat Builders","Sunrise Works","Nirman Co.","Ganga Contractors","Vikas Projects","Shree Civil","Delta Constructions"];
const STS=["Proposed","Sanctioned","In Progress","Delayed","Completed","Under Review","Cancelled"],W=[.3,.25,.2,.15,.1],FN=["Cost deviation","Schedule delay","Fund-utilization anomaly","Vendor frequency","Progress deviation"],mo=["Apr","May","Jun","Jul","Aug","Sep"];
let sa=[];for(let i=0;i<248;i++)sa.push(i<142?"Completed":i<229?"In Progress":"Delayed");
for(let i=247;i>0;i--){const j=ri(0,i);[sa[i],sa[j]]=[sa[j],sa[i]]}
const hi=new Set();while(hi.size<19)hi.add(ri(0,247));
const P=sa.map((status,i)=>{const state=SN[ri(0,7)],dist=ST[state][ri(0,ST[state].length-1)],con=dist+(R()<.5?" North":" South"),cat=CATS[ri(0,9)],sanct=ri(20,200)*1e5,prog=status=="Completed"?100:status=="Delayed"?ri(20,60):ri(30,90),util=Math.round(sanct*(status=="Completed"?.6+R()*.35:.3+R()*.4)),f=FN.map(()=>hi.has(i)?ri(75,100):ri(15,65)),m=ri(0,5);
return{id:"MP-"+(1000+i),name:cat+" – Phase "+ri(1,3),cat,state,dist,con,sanct,util,prog,status,f,score:Math.round(f.reduce((a,x,k)=>a+x*W[k],0)),vendor:VEN[ri(0,7)],m,upd:"2026-0"+(4+m)+"-"+String(ri(1,28)).padStart(2,"0")}});
const PM=Object.fromEntries(P.map(p=>[p.id,p])),TY=["Anomaly","Fraud Suspicion","Inefficiency"],AS=["Open","Under Review","Investigating","Resolved"],A=[];
P.forEach((p,i)=>{if(p.score>=40)A.push({id:"AL-"+(A.length+1),pid:p.id,type:p.score>=70?(i%2?"Fraud Suspicion":"Anomaly"):TY[i%3],score:p.score,status:AS[i%4],date:p.upd})});
let TH=ls("th",{m:40,h:70,c:90}),F={s:"",d:"",c:"",st:"",r:""},G={...F},NS=ls("ns",{});
const lvl=s=>s>=TH.c?"Critical":s>=TH.h?"High":s>=TH.m?"Medium":"Low",rb=l=>`<span class="bd ${l}">${{Low:"✓",Medium:"●",High:"▲",Critical:"⚠"}[l]} ${l}</span>`;
const fmt=n=>n>=1e7?"₹"+(n/1e7).toFixed(2)+" Cr":"₹"+Math.round(n/1e5)+" L",pct=(a,b)=>b?Math.round(100*a/b):0,sum=(a,k)=>a.reduce((x,p)=>x+p[k],0);
const fp=()=>P.filter(p=>(!F.s||p.state==F.s)&&(!F.d||p.dist==F.d)&&(!F.c||p.con==F.c)&&(!F.st||p.status==F.st)&&(!F.r||lvl(p.score)==F.r));
const aRows=(L,t)=>{const ids=new Set(L.map(p=>p.id));return A.filter(a=>ids.has(a.pid)&&(!t||a.type==t)).map(a=>{const p=PM[a.pid];return{...a,name:p.name,dist:p.dist,state:p.state,con:p.con,risk:lvl(a.score)}})};
const hd=(t,s)=>`<h2>${t}</h2><p class="nt">${s}</p>`;
function toast(m){const t=$("#ts");t.textContent=m;t.className="on";setTimeout(()=>t.className="",2200)}
function modal(h){$("#md").innerHTML=h?`<div class="ov" onclick="if(event.target==this)modal()"><div class="mo" role="dialog" aria-modal="true">${h}<p><button onclick="modal()">Close</button></p></div></div>`:""}
function go(h,f){Object.assign(F,f||{});G={...F};if(location.hash=="#"+encodeURI(h))route();else location.hash=h}
/* filters */
const LB={s:"State",d:"District",c:"Constituency",st:"Status",r:"Risk"};
function fb(){const ds=G.s?ST[G.s]:SN.flatMap(s=>ST[s]),cs=(G.d?[G.d]:ds).flatMap(d=>[d+" North",d+" South"]);
const S=(k,a)=>`<label>${LB[k]}<select onchange="G.${k}=this.value;${k=="s"?"G.d='';G.c=''":k=="d"?"G.c=''":""};$('#fb').innerHTML=fb()">${["",...a].map(v=>`<option value="${v}" ${G[k]==v?"selected":""}>${v||"All"}</option>`).join("")}</select></label>`;
return`<div class="card fbar">${S("s",SN)}${S("d",ds)}${S("c",cs)}${S("st",STS)}${S("r",["Low","Medium","High","Critical"])}<button class="p" onclick="F={...G};route()">Apply Filter</button><button onclick="F={s:'',d:'',c:'',st:'',r:''};G={...F};route()">Reset Filters</button></div><div class="chips">${Object.entries(F).filter(e=>e[1]).map(([k,v])=>`<button onclick="F.${k}='';G={...F};route()">✕ ${LB[k]}: ${v}</button>`).join("")}</div>`}
/* table engine: search, sort, pagination, CSV */
const T={},TB={};
function tbl(id,rows,cols,click){TB[id]={rows,cols,click};T[id]=T[id]||{q:"",k:"",d:1,pg:0,ps:10};const t=T[id];
return`<div class="card"><div class="bar"><input type="search" aria-label="Search table" placeholder="Search…" value="${t.q.replace(/"/g,"&quot;")}" oninput="T['${id}'].q=this.value;T['${id}'].pg=0;draw('${id}')"><select aria-label="Rows per page" onchange="T['${id}'].ps=+this.value;T['${id}'].pg=0;draw('${id}')">${[5,10,25,50].map(n=>`<option ${t.ps==n?"selected":""}>${n}</option>`).join("")}</select><button onclick="csv('${id}')">Export CSV</button></div><div id="t-${id}"></div></div>`}
function srt(id,k){const t=T[id];t.d=t.k==k?-t.d:1;t.k=k;draw(id)}
function draw(id){const e=$("#t-"+id);if(!e||!TB[id])return;const{rows,cols,click}=TB[id],t=T[id];let r=rows;
if(t.q){const q=t.q.toLowerCase();r=r.filter(x=>JSON.stringify(Object.values(x)).toLowerCase().includes(q))}
if(t.k)r=[...r].sort((a,b)=>(a[t.k]>b[t.k]?1:a[t.k]<b[t.k]?-1:0)*t.d);
const n=r.length,pg=Math.max(1,Math.ceil(n/t.ps));t.pg=Math.min(t.pg,pg-1);const v=r.slice(t.pg*t.ps,(t.pg+1)*t.ps);
e.innerHTML=`<div class="sc"><table><tr>${cols.map(c=>`<th><button class="th" onclick="srt('${id}','${c[1]}')">${c[0]}${t.k==c[1]?(t.d>0?" ▲":" ▼"):""}</button></th>`).join("")}</tr>${v.map(x=>`<tr ${click?`tabindex="0" onclick="${click}('${x.pid||x.id}')" onkeydown="if(event.key=='Enter')${click}('${x.pid||x.id}')"`:""}>${cols.map(c=>`<td>${c[2]?c[2](x):x[c[1]]}</td>`).join("")}</tr>`).join("")||`<tr><td>No matching records.</td></tr>`}</table></div><div class="bar">${n} records · Page ${t.pg+1}/${pg}<button ${t.pg?"":"disabled"} onclick="T['${id}'].pg--;draw('${id}')">Prev</button><button ${t.pg<pg-1?"":"disabled"} onclick="T['${id}'].pg++;draw('${id}')">Next</button></div>`}
function csv(id){const{rows,cols}=TB[id],e=v=>'"'+String(v).replace(/"/g,'""')+'"',s=[cols.map(c=>e(c[0])).join(","),...rows.map(r=>cols.map(c=>e(r[c[1]])).join(","))].join("\n");
modal(`<h3>CSV export (${rows.length} rows)</h3><textarea id="cv" readonly rows="10" style="width:100%">${s.replace(/&/g,"&amp;").replace(/</g,"&lt;")}</textarea><p><button class="p" onclick="cv.select();try{navigator.clipboard.writeText(cv.value);toast('CSV copied.')}catch(e){}">Copy CSV</button></p>`)}
/* project detail */
function openP(id){const p=PM[id],al=A.filter(a=>a.pid==id);
modal(`<h3>${p.id} · ${p.name}</h3><p>${rb(lvl(p.score))} ${p.state} › ${p.dist} › ${p.con} · Vendor: ${p.vendor}</p><p>Sanctioned ${fmt(p.sanct)} · Utilized ${fmt(p.util)} (${pct(p.util,p.sanct)}%) · Progress ${p.prog}%</p>
<label>Status <select onchange="PM['${id}'].status=this.value;toast('Project updated successfully.');route()">${STS.map(s=>`<option ${s==p.status?"selected":""}>${s}</option>`).join("")}</select></label>
<h3>Demo AI Risk Model · score ${p.score}</h3>${FN.map((n,k)=>`<div class="fr"><span>${n} (weight ${W[k]*100}%)</span><span class="pb" style="width:100px"><i style="width:${p.f[k]}%"></i></span><b>${p.f[k]}</b></div>`).join("")}
<p>Alerts: ${al.map(a=>`${a.id} (${a.type}, ${a.status})`).join("; ")||"none"}</p><p class="nt">AI-generated indicator from synthetic data. Requires human verification; not proof of wrongdoing.</p>`)}
/* views */
const AC=[["Alert","id"],["Project","pid"],["Name","name"],["District","dist"],["State","state"],["Type","type"],["Score","score"],["Risk","risk",x=>rb(x.risk)],["Status","status"],["Date","date"]];
function dash(){const L=fp();if(!L.length)return`<div id="fb">${fb()}</div><div class="card">No projects match the current filters.</div>`;
const kp=(t,v,s,g)=>`<button class="card kp" onclick="${g}"><small>${t}</small><b>${v}</b><span>${s}</span></button>`,hr=L.filter(p=>p.score>=TH.h).length,avg=Math.round(sum(L,"score")/L.length),ar=aRows(L);
const c=mo.map((_,m)=>L.filter(p=>p.m==m&&p.status=="Completed").length),o=mo.map((_,m)=>L.filter(p=>p.m==m&&p.status!="Completed").length),u=mo.map((_,m)=>{const q=L.filter(p=>p.m==m);return q.length?100*sum(q,"util")/sum(q,"sanct"):0}),mx=Math.max(1,...c,...o);
const chart=`<svg viewBox="0 0 420 210" width="100%" role="img" aria-label="Projects completed, ongoing and fund utilization by month">${mo.map((n,m)=>{const x=25+m*65;return`<rect x="${x}" y="${170-c[m]/mx*150}" width="20" height="${c[m]/mx*150}" fill="var(--p)"><title>${n}: ${c[m]} completed</title></rect><rect x="${x+22}" y="${170-o[m]/mx*150}" width="20" height="${o[m]/mx*150}" fill="#8fb8f5"><title>${n}: ${o[m]} ongoing</title></rect><text x="${x+10}" y="190" font-size="11" fill="var(--m)">${n}</text>`}).join("")}<polyline fill="none" stroke="#19A974" stroke-width="2" points="${u.map((v,m)=>`${45+m*65},${170-v*1.5}`).join(" ")}"/>${u.map((v,m)=>`<circle cx="${45+m*65}" cy="${170-v*1.5}" r="3" fill="#19A974"><title>${mo[m]}: ${Math.round(v)}% utilization</title></circle>`).join("")}</svg><p class="nt">■ Completed &nbsp;<span style="color:#8fb8f5">■</span> Ongoing &nbsp;<span style="color:#19A974">●</span> Fund utilization %</p>`;
const cn=TY.map(t=>ar.filter(a=>a.type==t).length),tot=cn.reduce((a,b)=>a+b,0)||1,col=["#E5484D","#F5A623","#1465D8"],lk=["alerts/Anomaly","alerts/Fraud Suspicion","alerts/Inefficiency"];let acc=0;
const donut=`<svg viewBox="0 0 100 100" width="150" role="img" aria-label="Alert breakdown">${cn.map((n,i)=>{const l=n/tot*251.3,s=`<circle cx="50" cy="50" r="40" fill="none" stroke="${col[i]}" stroke-width="16" stroke-dasharray="${l} ${251.3-l}" stroke-dashoffset="${-acc}" transform="rotate(-90 50 50)" style="cursor:pointer" onclick="go('${lk[i]}')"><title>${TY[i]}: ${n}</title></circle>`;acc+=l;return s}).join("")}<text x="50" y="52" text-anchor="middle" font-size="16" font-weight="700" fill="var(--n)">${tot==1&&!ar.length?0:tot}</text></svg><div class="lg">${TY.map((t,i)=>`<p><span style="color:${col[i]}">●</span> <a onclick="go('${lk[i]}')">${t}</a>: ${cn[i]}</p>`).join("")}</div>`;
const rs=SN.map(s=>{const q=L.filter(p=>p.state==s);return q.length?{s,a:Math.round(sum(q,"score")/q.length),n:q.length}:null}).filter(Boolean).sort((a,b)=>b.a-a.a).slice(0,5);
const top=k=>[...L].sort((a,b)=>b.f[k]-a.f[k])[0],vc={};L.filter(p=>p.score>=TH.h).forEach(p=>vc[p.vendor]=(vc[p.vendor]||0)+1);const tv=Object.entries(vc).sort((a,b)=>b[1]-a[1])[0],t0=top(0),t1=top(1);
const ins=(i,t,x,id)=>`<button class="ins" onclick="openP('${id}')"><b>${i} ${t}</b><br><span class="nt">${x}</span></button>`;
T.ra=T.ra||{q:"",k:"date",d:-1,pg:0,ps:5};
return`<div id="fb">${fb()}</div><div class="g k">${kp("Total MPLAD Projects",L.length,"↑ 12% vs prev 6 mo (demo)","go('projects')")}${kp("Projects Completed",L.filter(p=>p.status=="Completed").length,"↑ 18% (demo)","go('projects',{st:'Completed'})")}${kp("Active Projects",L.filter(p=>p.status=="In Progress").length,"↑ 5% (demo)","go('projects',{st:'In Progress'})")}${kp("High-Risk Projects",hr,"↑ 32% (demo)","go('projects',{r:'High'})")}${kp("Fund Utilization",pct(sum(L,"util"),sum(L,"sanct"))+"%","↑ 7% (demo)","go('projects')")}${kp("AI Risk Score",avg,lvl(avg)+" risk","go('alerts')")}</div>
<div class="g g2"><div class="card"><h3>Project Progress &amp; Fund Utilization</h3>${chart}</div><div class="card"><h3>AI Alert Breakdown</h3>${donut}</div><div class="card"><h3>Top Risk States</h3>${rs.map((r,i)=>`<p><button class="ins" onclick="go('dashboard',{s:'${r.s}',d:'',c:''})">${i+1}. ${r.s} — avg ${r.a} ${rb(lvl(r.a))} · ${r.n} projects</button></p>`).join("")}<p class="nt">Ranked from the dataset. Click a state to filter.</p></div></div>
<div class="g g2"><div><h3>Recent AI Alerts <button onclick="go('alerts')">View All</button></h3>${tbl("ra",ar,AC,"openP")}</div><div class="card"><h3>AI Insights <span class="nt">(AI-generated, needs human verification)</span></h3>${ins("💰","Potential cost deviation",`${t0.id} ${t0.name}: cost-deviation factor ${t0.f[0]}/100`,t0.id)}${ins("⏱","Potential schedule delay",`${t1.id} ${t1.name}: schedule factor ${t1.f[1]}/100, progress ${t1.prog}%`,t1.id)}${tv?`<p class="nt">Potential vendor pattern: ${tv[0]} appears in ${tv[1]} high-risk projects.</p>`:""}<h3>Quick Actions</h3><div class="bar"><button class="p" onclick="go('alerts')">Review Alerts</button><button onclick="go('projects',{r:'High'})">High-Risk Projects</button><button onclick="go('reports')">Generate Report</button><button onclick="go('alerts/Anomaly')">Anomalies</button><button onclick="go('alerts/Fraud Suspicion')">Fraud Alerts</button></div></div></div>`}
function proj(){const L=fp();T.pj=T.pj||{q:"",k:"",d:1,pg:0,ps:10};return hd("Projects","Search, sort, filter and click a row for details and status update.")+`<div id="fb">${fb()}</div>`+tbl("pj",L.map(p=>({...p,risk:lvl(p.score)})),[["ID","id"],["Name","name"],["State","state"],["District","dist"],["Constituency","con"],["Sanctioned","sanct",x=>fmt(x.sanct)],["Utilized","util",x=>fmt(x.util)],["Progress","prog",x=>`<span class="pb"><i style="width:${x.prog}%"></i></span> ${x.prog}%`],["Status","status"],["Risk","risk",x=>rb(x.risk)],["Updated","upd"]],"openP")}
function alr(t){const L=fp(),ar=aRows(L,t),TT={Anomaly:"Anomaly Detection","Fraud Suspicion":"Fraud Alerts",Inefficiency:"Inefficiencies"};
return hd(TT[t]||"Recent AI Alerts","AI-generated indicators requiring human review — potential anomalies and risk patterns, not confirmed findings.")+`<div id="fb">${fb()}</div><div class="g k"><div class="card kp"><small>Total</small><b>${ar.length}</b></div><div class="card kp"><small>Open</small><b>${ar.filter(a=>a.status=="Open").length}</b></div><div class="card kp"><small>High / Critical</small><b>${ar.filter(a=>a.score>=TH.h).length}</b></div><div class="card kp"><small>Resolved</small><b>${ar.filter(a=>a.status=="Resolved").length}</b></div></div>`+tbl("al"+(t||""),ar,AC,"openP")}
function rep(){return hd("Reports","Generated from the current filtered dataset. Use Print to save as PDF.")+`<div id="fb">${fb()}</div><div class="card bar"><label>Report type <select onchange="RT=this.value;RG=0;route()">${["State Performance","Fund Utilization by Category","Risk Assessment"].map(x=>`<option ${x==RT?"selected":""}>${x}</option>`).join("")}</select></label><button class="p" onclick="genR()">Generate Report</button><button onclick="print()">Print</button></div><div id="rp">${RG?rpv():"<p>Choose a report type and click Generate Report.</p>"}</div>`}
let RT="State Performance",RG=0;
function genR(){$("#rp").innerHTML="<p>Generating report…</p>";setTimeout(()=>{RG=1;$("#rp").innerHTML=rpv();draw("rep");toast("Report generated successfully.")},600)}
function rpv(){const L=fp(),g=(k,a)=>a.map(v=>{const q=L.filter(p=>p[k]==v);return q.length?{name:v,projects:q.length,completed:q.filter(p=>p.status=="Completed").length,high_risk:q.filter(p=>p.score>=TH.h).length,sanctioned:fmt(sum(q,"sanct")),utilization:pct(sum(q,"util"),sum(q,"sanct"))+"%",avg_risk:Math.round(sum(q,"score")/q.length)}:null}).filter(Boolean);
const gc=["name","projects","completed","high_risk","sanctioned","utilization","avg_risk"].map(k=>[k.replace("_"," "),k]);
if(RT=="Risk Assessment")return tbl("rep",L.filter(p=>p.score>=TH.m).map(p=>({id:p.id,name:p.name,state:p.state,dist:p.dist,score:p.score,risk:lvl(p.score),status:p.status})),[["ID","id"],["Name","name"],["State","state"],["District","dist"],["Score","score"],["Risk","risk"],["Status","status"]]);
return tbl("rep",RT=="State Performance"?g("state",SN):g("cat",CATS),gc)}
function set(){const TG=["Email alerts","Fraud alerts","Anomaly alerts","Report generation","Anomaly detection","Fraud indicators","Cost analysis","Vendor analysis"],th=ls("theme","auto");
return hd("Settings","Saved in this browser (localStorage).")+`<div class="g g2"><div class="card"><h3>Appearance</h3><select onchange="sv('theme',this.value);applyT()">${["auto","light","dark"].map(x=>`<option ${x==th?"selected":""}>${x}</option>`).join("")}</select></div><div class="card"><h3>Risk thresholds (0–100)</h3>${[["m","Medium from"],["h","High from"],["c","Critical from"]].map(([k,l])=>`<p><label>${l} <input type="number" min="1" max="100" value="${TH[k]}" onchange="TH.${k}=+this.value;sv('th',TH);toast('Thresholds saved.');route()"></label></p>`).join("")}<p class="nt">Low is below Medium. Changes re-classify all projects.</p></div><div class="card"><h3>Notifications &amp; AI options</h3>${TG.map(k=>`<p><label><input type="checkbox" ${NS[k]===false?"":"checked"} onchange="NS['${k}']=this.checked;sv('ns',NS)"> ${k}</label></p>`).join("")}</div></div>`}
const RO=["Super Admin","Admin","State Officer","Auditor","Viewer"],PR=["View Dashboard","Edit Projects","Resolve Alerts","Generate Reports","Manage Users","View Audit Logs"],DF={"Super Admin":PR,Admin:PR,"State Officer":PR.slice(0,4),Auditor:["View Dashboard","Generate Reports","View Audit Logs"],Viewer:["View Dashboard"]};let PX=ls("px",null)||Object.fromEntries(RO.flatMap(r=>PR.map(p=>[r+"|"+p,DF[r].includes(p)])));
function adm(){const U=[["Asha Verma","Super Admin","All"],["Ravi Kumar","Admin","All"],["Neha Singh","State Officer","Bihar"],["Imran Khan","State Officer","Uttar Pradesh"],["Meena Rao","Auditor","All"],["Tarun Das","Viewer","Gujarat"]].map(([n,r,s],i)=>({name:n,email:n.split(" ")[0].toLowerCase()+"@example.test",role:r,state:s,status:i==5?"Inactive":"Active",login:"2026-09-"+(10+i)}));
return hd("Admin","Demo user list and role permission matrix (permissions are stored, not enforced).")+tbl("us",U,[["Name","name"],["Email","email"],["Role","role"],["State","state"],["Status","status"],["Last login","login"]])+`<div class="card"><h3>Role permissions</h3><div class="sc"><table><tr><th>Permission</th>${RO.map(r=>`<th>${r}</th>`).join("")}</tr>${PR.map(p=>`<tr><td>${p}</td>${RO.map(r=>`<td><input type="checkbox" aria-label="${r}: ${p}" ${PX[r+"|"+p]?"checked":""} onchange="PX['${r}|${p}']=this.checked;sv('px',PX)"></td>`).join("")}</tr>`).join("")}</table></div></div>`}
/* shell */
const NV=[["Dashboard","dashboard"],["Projects","projects"],["Anomaly Detection","alerts/Anomaly"],["Fraud Alerts","alerts/Fraud Suspicion"],["Inefficiencies","alerts/Inefficiency"],["Reports","reports"],["Settings","settings"],["Admin","admin"]];
function route(){const h=decodeURIComponent(location.hash.slice(1)||"dashboard"),[v,a]=h.split("/"),V={dashboard:dash,projects:proj,alerts:()=>alr(a),reports:rep,settings:set,admin:adm};
$("#main").innerHTML=(V[v]||dash)();$("#nv").innerHTML=NV.map(([l,x])=>`<a href="#${encodeURI(x)}" class="${x==h||(!h&&x=="dashboard")?"on":""}">${l}</a>`).join("");
$("#bell").textContent="🔔 "+A.filter(x=>x.status=="Open"&&x.score>=TH.h).length;Object.keys(TB).forEach(draw);scrollTo(0,0)}
function applyT(){const t=ls("theme","auto");t=="auto"?document.documentElement.removeAttribute("data-theme"):document.documentElement.dataset.theme=t}
$("#bell").onclick=()=>go("alerts/Fraud Suspicion");$("#gs").onkeydown=e=>{if(e.key=="Enter"){T.pj=Object.assign(T.pj||{k:"",d:1,pg:0,ps:10},{q:e.target.value,pg:0});F={s:"",d:"",c:"",st:"",r:""};go("projects")}};
addEventListener("hashchange",route);applyT();route();
